# <font color='blue'>Data Science Academy</font>
# <font color='blue'>Matemática Para Data Science</font>

## <font color='blue'>Determinando os Autovetores e Autovalores de Uma Matriz em Python</font>

In [1]:
# Versão da Linguagem Python
# Você pode usar a versão indicada nos vídeos ou a versão abaixo!
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.9.18


In [ ]:
# Para atualizar um pacote, execute o comando abaixo no terminal ou prompt de comando:
# pip install -U nome_pacote

# Para instalar a versão exata de um pacote, execute o comando abaixo no terminal ou prompt de comando:
# !pip install nome_pacote==versão_desejada

# Depois de instalar ou atualizar o pacote, reinicie o jupyter notebook.

# Instala o pacote watermark. 
# Esse pacote é usado para gravar as versões de outros pacotes usados neste jupyter notebook.
# !pip install -q -U watermark

In [2]:
# Imports
import numpy as np

In [3]:
# Versões dos pacotes usados neste jupyter notebook
%reload_ext watermark
%watermark -a "Data Science Academy" --iversions

Author: Data Science Academy

numpy: 1.26.3



## Determinando os Autovetores e Autovalores de Uma Matriz em Python

In [4]:
# Definindo a matriz A
A = np.array([[-4, -2],
             [1, 1]])

print(A)

[[-4 -2]
 [ 1  1]]


In [5]:
# Calculando autovalores e autovetores
autovalores, autovetores = np.linalg.eig(A)

In [6]:
print("Matriz A:")
print(A)
print("\nAutovalores:")
print(autovalores)
print("\nAutovetores:")
print(autovetores)

Matriz A:
[[-4 -2]
 [ 1  1]]

Autovalores:
[-3.56155281  0.56155281]

Autovetores:
[[-0.97680334  0.40154681]
 [ 0.21413834 -0.9158385 ]]


# Fim