# <font color='blue'>Data Science Academy - Matemática Para Data Science</font>

In [1]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.9.18


In [2]:
# Para atualizar um pacote, execute o comando abaixo no terminal ou prompt de comando:
# pip install -U nome_pacote

# Para instalar a versão exata de um pacote, execute o comando abaixo no terminal ou prompt de comando:
# !pip install nome_pacote==versão_desejada

# Depois de instalar ou atualizar o pacote, reinicie o jupyter notebook.

# Instala o pacote watermark. 
# Esse pacote é usado para gravar as versões de outros pacotes usados neste jupyter notebook.
# !pip install -q -U watermark

In [3]:
import numpy as np

In [4]:
# Versões dos pacotes usados neste jupyter notebook
%reload_ext watermark
%watermark -a "Data Science Academy" --iversions

Author: Data Science Academy

numpy: 1.26.3



## Multiplicação de Matrizes

### Multiplicação Element-wise

Já vimos a multiplicação de matrizes com element-wise. Apenas para relembrar:

In [5]:
# Definimos uma matriz
m = np.array([[1,2,3], [4,5,6]])
print(m)

[[1 2 3]
 [4 5 6]]


In [6]:
m.shape

(2, 3)

In [7]:
# Usamos o operador de multiplicação para multiplicar cada elemento da matriz por 3. 
# Isso vai gerar uma nova matriz n.
n = m * 3
print(n)

[[ 3  6  9]
 [12 15 18]]


In [9]:
n.shape

(2, 3)

In [10]:
# Multiplicamos as duas matrizes, element-wise
matriz_resultado = m * n

In [11]:
print(matriz_resultado)

[[  3  12  27]
 [ 48  75 108]]


In [12]:
matriz_resultado.shape

(2, 3)

### MatMul x Dot

> Imagine agora que precisamos multiplicar as duas matrizes abaixo:

In [13]:
a = np.array([[1,2,3,4], [5,6,7,8]])

In [14]:
a.shape

(2, 4)

In [15]:
b = np.array([[1,2,3], [4,5,6], [7,8,9],[10,11,12]])

In [16]:
b.shape

(4, 3)

In [17]:
a * b

ValueError: operands could not be broadcast together with shapes (2,4) (4,3) 

In [18]:
# Essa notação é a mesma coisa que matmul()
a @ b

array([[ 70,  80,  90],
       [158, 184, 210]])

In [19]:
np.matmul(a, b)

array([[ 70,  80,  90],
       [158, 184, 210]])

In [20]:
np.dot(a, b)

array([[ 70,  80,  90],
       [158, 184, 210]])

> Porém, quando lidamos com arrays multidimensionais (N > 2) o resultado é um pouco diferente. Você pode ver a diferença abaixo.

In [21]:
# Dois arrays de 3 dimensões cada um
a = np.random.rand(2,3,3)
b = np.random.rand(2,3,3)

In [22]:
a.shape

(2, 3, 3)

In [23]:
b.shape

(2, 3, 3)

In [24]:
c = np.matmul(a, b)

In [25]:
d = np.dot(a, b)

In [26]:
print(c, c.shape)

[[[0.4545829  0.33738885 0.10603533]
  [0.92789729 0.69567694 0.24533381]
  [1.30367575 0.92990304 0.44934887]]

 [[0.42966312 0.18126919 0.08175891]
  [1.2766012  0.57311193 0.52378141]
  [0.63142386 0.41933264 0.16172924]]] (2, 3, 3)


In [27]:
print(d, d.shape)

[[[[0.4545829  0.33738885 0.10603533]
   [0.4884041  0.19803509 0.10988705]]

  [[0.92789729 0.69567694 0.24533381]
   [0.85092649 0.38580989 0.20230561]]

  [[1.30367575 0.92990304 0.44934887]
   [0.93281504 0.48463969 0.27709424]]]


 [[[0.388503   0.31369622 0.06546364]
   [0.42966312 0.18126919 0.08175891]]

  [[1.83421688 1.05194002 0.86551423]
   [1.2766012  0.57311193 0.52378141]]

  [[1.08240311 0.86559514 0.32543635]
   [0.63142386 0.41933264 0.16172924]]]] (2, 3, 2, 3)


**Atenção:**

- A função matmul() usa o array como uma pilha de matrizes como elementos que residem nos dois últimos índices, respectivamente. 

- A função dot(), por outro lado, realiza a multiplicação como a soma dos produtos sobre o último eixo da primeira matriz e o penúltimo da segunda.

- Outra diferença entre matmul() e a função numpy.dot é que a função matmul() não pode realizar multiplicação de array com valores escalares.

Vamos ver mais exemplos.

### Matrix Product

https://numpy.org/doc/stable/reference/generated/numpy.matmul.html

A definição de multiplicação de matrizes indica uma multiplicação linha por coluna, onde as entradas na i-ésima linha de A são multiplicados pelas entradas correspondentes no jth coluna de B e, em seguida, somando os resultados.

A multiplicação de matrizes NÃO é comutativa.

Para encontrar o produto da matriz, você usa a função matmul() do NumPy. **O shape das matrizes precisa ser compatível.**

**Aqui estão as regras para o produto das matrizes:**

•	O número de colunas na matriz esquerda deve ser igual ao número de linhas na matriz direita (logo, a ordem das matrizes na multiplicação é importante).

•	A matriz resultante da operação possui o mesmo número de linhas que a matriz esquerda e o mesmo número de colunas que a matriz direita.

•	Ordem importa aqui. Multiplicar A • B não é o mesmo que multiplicar B • A.

•	Os dados na matriz esquerda devem ser organizados como linhas, enquanto os dados na matriz direita devem ser organizados como colunas.


In [28]:
# Não podemos usar matmul nas matrizes do exemplo anterior pois viola uma das regras
np.matmul(m, n)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [29]:
a = np.array([[1,2,3,4], [5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [30]:
a.shape

(2, 4)

In [31]:
b = np.array([[1,2,3],[4,5,6],[7,6,9],[10,11,12]])
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  6  9]
 [10 11 12]]


In [32]:
b.shape

(4, 3)

In [33]:
# Matrix Product
matriz_resposta = np.matmul(a, b)

In [34]:
print(matriz_resposta)

[[ 70  74  90]
 [158 170 210]]


In [35]:
matriz_resposta.shape

(2, 3)

In [36]:
# Se as matrizes tiverem shape incompatível, você recebe a mensagem de erro abaixo.
np.matmul(b, a)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

### Dot Product

https://numpy.org/doc/stable/reference/generated/numpy.dot.html

O produto escalar (dot product) é a soma dos produtos dos elementos correspondentes nas duas matrizes. Para obter o produto escalar, o número de colunas da primeira matriz deve ser igual ao número de linhas da segunda matriz.

O mesmo problema do exemplo anterior aconteceria aqui devido à diferença nos shapes.

In [37]:
np.dot(b, a)

ValueError: shapes (4,3) and (2,4) not aligned: 3 (dim 1) != 2 (dim 0)

Agora sim:

In [38]:
np.dot(a, b)

array([[ 70,  74,  90],
       [158, 170, 210]])

> Dot product com escalares:

In [39]:
# Dois escalares
k = 5
j = 7

print(np.dot(k, j))

35


> Dot product com vetores:

In [40]:
# Vetores
c = [3,4,5]
d = [6,7,8]

print(np.dot(c, d))

86


> Dot product com matrizes:

In [41]:
# Matrizes
m1 = [[2, 1], [0, 3]]
m2 = [[1, 1], [3, 2]]
print(np.dot(m1, m2))

[[5 4]
 [9 6]]


> Dot product com matrizes (se inverter a ordem o resultado é diferente):

In [42]:
print(np.dot(m2, m1))

[[2 4]
 [6 9]]


In [43]:
z = np.array([[1,2],[3,4]])
print(z)

[[1 2]
 [3 4]]


In [44]:
np.dot(z, z)

array([[ 7, 10],
       [15, 22]])

In [45]:
# Podemos chamar a função dot() diretamente do objeto ndarray
z.dot(z)

array([[ 7, 10],
       [15, 22]])

In [46]:
# Matmul gera o mesmo resultado porque as dimensões são as mesmas (mesma matriz)
np.matmul(z, z)

array([[ 7, 10],
       [15, 22]])

Resumindo, o produto escalar é a soma dos produtos de valores em dois vetores de mesmo tamanho e a multiplicação de matrizes é uma versão matricial do produto escalar com duas matrizes.

## Fim