# <font color='blue'>Data Science Academy - Matemática Para Data Science</font>

In [1]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.9.18


In [ ]:
# Para atualizar um pacote, execute o comando abaixo no terminal ou prompt de comando:
# pip install -U nome_pacote

# Para instalar a versão exata de um pacote, execute o comando abaixo no terminal ou prompt de comando:
# !pip install nome_pacote==versão_desejada

# Depois de instalar ou atualizar o pacote, reinicie o jupyter notebook.

# Instala o pacote watermark. 
# Esse pacote é usado para gravar as versões de outros pacotes usados neste jupyter notebook.
# !pip install -q -U watermark

In [2]:
# Imports
import numpy as np
import sympy as sym

In [4]:
# Versões dos pacotes usados neste jupyter notebook
%reload_ext watermark
%watermark -a "Data Science Academy" --iversions

Author: Data Science Academy

sympy: 1.12
numpy: 1.26.3



## Calculando o Determinante com NumPy e SymPy

In [8]:
# Cria uma matriz 2x2
matrix = np.array([[1, 2], [3, 4]])

In [9]:
# Calcula o determinante
determinante_1 = np.linalg.det(matrix)

In [10]:
print(determinante_1)

-2.0000000000000004


In [12]:
# Cria uma matriz 2x2
matrix = sym.Matrix([[1, 2], [3, 4]])

In [13]:
# Calcula o determinante
determinante_2 = matrix.det()

In [14]:
print(determinante_2)

-2


Fómula do determinante:

Considerando uma matriz 2 x 2 com os elementos
   

In [19]:
# Cria uma matriz 2x2 de exemplo
matrix = np.array([['a', 'b'], ['c', 'd']])

In [20]:
print(matrix)

[['a' 'b']
 ['c' 'd']]


Calculamos o determinante assim:

|Det| = ad − bc

In [21]:
# Cria uma matriz 2x2
matrix = np.array([[1, 2], [3, 4]])

In [22]:
print(matrix)

[[1 2]
 [3 4]]


In [23]:
# Calculando o determinante com operações aritméticas
determinante_3 = (1 * 4) - (2 * 3)

In [24]:
determinante_3

-2

> E para matriz com 3 dimensões?

In [25]:
b = np.array([[6,1,1], [4, -2, 5], [2, 8, 7]])

In [26]:
print(b)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]


In [27]:
print(np.linalg.det(b))

-306.0


In [28]:
print(6*(-2*7 - 5*8) - 1*(4*7 - 5*2) + 1*(4*8 - -2*2))

-306


Fórmula para outras dimensões:

https://www.mathsisfun.com/algebra/matrix-determinant.html

## Matriz Inversa

A matriz inversa é uma matriz que, quando multiplicada por uma matriz dada, produz a matriz identidade. A matriz identidade é uma matriz quadrada com 1s na diagonal principal e 0s em todas as outras posições.

Por exemplo, se A é uma matriz quadrada e A^-1 é sua matriz inversa, então AA^-1 = A^-1A = I, onde I é a matriz identidade.

A inversa de uma matriz só existe se a matriz é não-singular, ou seja, se o determinante da matriz é diferente de zero. Matrizes singulares não possuem inversa.

Existem vários métodos para calcular a inversa de uma matriz, como a decomposição LU, a decomposição QR, e a eliminação gaussiana. Algumas bibliotecas científicas, como o NumPy, também fornecem funções para calcular a inversa de uma matriz, como a função numpy.linalg.inv().

Aqui está um exemplo de como calcular a matriz inversa de uma matriz 2x2:

In [29]:
matriz = np.array([[1, 2], [3, 4]])

In [30]:
inversa = np.linalg.inv(matriz)

In [31]:
print(inversa)

[[-2.   1. ]
 [ 1.5 -0.5]]


> Se o determinate de uma matriz é zero, ela não tem matriz inversa.

In [32]:
mat = np.array([[1, 2], [2, 4]])

In [34]:
print(np.linalg.det(mat))

0.0


In [35]:
# Observe o erro
inversa = np.linalg.inv(mat)

LinAlgError: Singular matrix

Leia o material em pdf na sequência do capítulo 6 do curso antes de prosseguir.

## Resolvendo Sistema de Equações Lineares com Eliminação Gaussiana em Python

Aqui está um exemplo de código Python que usa o pacote NumPy para escalonar uma matriz e resolver um sistema de equações lineares usando o método de eliminação gaussiana:

In [3]:
# Define a matriz do sistema
A = np.array([[3, 2, -1], [2, -2, 4], [-1, 1/2, -1]])

In [4]:
print(A)

[[ 3.   2.  -1. ]
 [ 2.  -2.   4. ]
 [-1.   0.5 -1. ]]


In [6]:
# Define o vetor de termos independentes
b = np.array([1, -2, 0])

In [7]:
print(b)

[ 1 -2  0]


In [9]:
# Escalonamento de matriz

# Percorre a primeira linha
for i in range(A.shape[0] - 1):
    
    # Percorre a primeira linha novamente
    for j in range(i+1, A.shape[0]):
        
        # Calcula o fator
        factor = A[j, i] / A[i, i]
        
        # Aplica o fator em A
        A[j, i:] = A[j, i:] - factor * A[i, i:]
        
        # Aplica o fator em B
        b[j] = b[j] - factor * b[i]

In [10]:
print(A)

[[ 3.          2.         -1.        ]
 [ 0.         -3.33333333  4.66666667]
 [ 0.          0.          0.3       ]]


In [11]:
print(b)

[ 1 -2  0]


In [12]:
# Matriz resultante
x = np.zeros(A.shape[0])

In [13]:
print(x)

[0. 0. 0.]


In [14]:
x[-1] = b[-1] / A[-1, -1]

In [15]:
print(x)

[0. 0. 0.]


In [18]:
# Resolução do sistema por substituição regressiva

# Loop pelo shape
for i in range(A.shape[0]-2, -1, -1):
    
    # Produto escalar
    x[i] = (b[i] - np.dot(A[i, i+1:], x[i+1:])) / A[i, i] 

In [19]:
# Imprime a solução
print(x)

[-0.06666667  0.6         0.        ]


## Fim