# <font color='blue'>Data Science Academy</font>
# <font color='blue'>Matemática Para Data Science</font>

## <font color='blue'>Gradiente Descendente via Operações Matemáticas com Linguagem Python</font>

In [ ]:
# Versão da Linguagem Python
# Você pode usar a versão indicada nos vídeos ou a versão abaixo!
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

In [ ]:
# Para atualizar um pacote, execute o comando abaixo no terminal ou prompt de comando:
# pip install -U nome_pacote

# Para instalar a versão exata de um pacote, execute o comando abaixo no terminal ou prompt de comando:
# !pip install nome_pacote==versão_desejada

# Depois de instalar ou atualizar o pacote, reinicie o jupyter notebook.

# Instala o pacote watermark. 
# Esse pacote é usado para gravar as versões de outros pacotes usados neste jupyter notebook.
# !pip install -q -U watermark

## Gradiente Descendente via Operações Matemáticas com Linguagem Python

Uma aplicação comum de derivadas em Data Science é na implementação do algoritmo de gradiente descendente, usado para otimizar funções de custo em modelos de aprendizado de máquina, como regressão linear ou redes neurais.

Aqui está um exemplo de como isso pode ser feito em Python para a tarefa de regressão linear. Para simplificar, vamos considerar uma regressão linear simples com apenas uma variável de entrada.

No exemplo abaixo, o código cria um conjunto de dados aleatório, inicializa os parâmetros da regressão linear de forma aleatória (a variável theta), e então executa o algoritmo de gradiente descendente por um número fixo de iterações.

A cada iteração, o algoritmo calcula o gradiente da função de custo em relação aos parâmetros (gradients) e, em seguida, atualiza os parâmetros na direção oposta ao gradiente (isso é o que a linha theta = theta - lr * gradients faz). O tamanho do passo é determinado pela taxa de aprendizado (lr).

Ao final do processo, os parâmetros da regressão linear (ou seja, a inclinação e o intercepto) são armazenados na variável theta. Esses parâmetros minimizam a função de custo e, portanto, representam a melhor linha de ajuste aos dados.

Considere que X é o diâmetro de uma Pizza e y a gorjeta dada por um cliente. Conseguimos prever a gorjeta com base no diâmetro da pizza?

Vamos definir uma relação linear entre X e y:

y = coef1 + (coef2 * X)

In [2]:
import numpy as np

In [3]:
# Criamos um conjunto de dados sintéticos
X = 2 * np.random.rand(100,1)
y = 4 + 3 * X + np.random.rand(100,1)

In [4]:
print(X)

[[1.56161685]
 [1.14319407]
 [1.71228807]
 [0.33859444]
 [0.43720796]
 [1.93338735]
 [0.86421959]
 [1.79714241]
 [0.63653245]
 [0.2927876 ]
 [0.67142068]
 [1.61191423]
 [1.46757444]
 [0.46405343]
 [0.55699032]
 [1.59740871]
 [0.53193138]
 [1.03197645]
 [0.90537829]
 [1.04465947]
 [0.52411079]
 [1.56455853]
 [0.02274901]
 [1.31363029]
 [1.8180172 ]
 [0.33801073]
 [0.9456321 ]
 [1.2385409 ]
 [1.52811015]
 [1.94679357]
 [1.18658316]
 [0.77768691]
 [0.05397329]
 [1.84263548]
 [0.93095793]
 [1.2282653 ]
 [0.17527323]
 [0.32074588]
 [0.14767358]
 [0.37664843]
 [0.61354231]
 [1.0246462 ]
 [1.25614367]
 [1.59294787]
 [1.92357421]
 [1.80601703]
 [1.99733149]
 [1.49917063]
 [0.58957174]
 [0.9451539 ]
 [0.24569318]
 [0.08314566]
 [0.37824846]
 [0.01490482]
 [0.83537067]
 [1.41473195]
 [1.52665682]
 [0.7189443 ]
 [1.05264904]
 [1.40535256]
 [1.65323662]
 [0.24688515]
 [0.7518369 ]
 [0.42893515]
 [0.56398652]
 [0.51123106]
 [1.97204861]
 [1.93073196]
 [0.44494656]
 [0.36270066]
 [1.39962525]
 [0.38

In [5]:
print(y)

[[ 9.47313687]
 [ 7.84088744]
 [ 9.63886891]
 [ 5.55080061]
 [ 6.10801257]
 [10.295818  ]
 [ 7.52349834]
 [ 9.93781981]
 [ 6.22781471]
 [ 5.3907905 ]
 [ 6.36072611]
 [ 8.88672221]
 [ 8.7881813 ]
 [ 6.11706884]
 [ 6.5337272 ]
 [ 8.88915925]
 [ 5.83843024]
 [ 8.0166442 ]
 [ 7.47508601]
 [ 7.79105091]
 [ 6.23665245]
 [ 9.68681413]
 [ 4.30919477]
 [ 8.33084011]
 [ 9.91925157]
 [ 5.19489745]
 [ 7.21875251]
 [ 7.97605798]
 [ 9.506101  ]
 [10.81232678]
 [ 8.30951232]
 [ 6.94027664]
 [ 4.27968554]
 [ 9.87110687]
 [ 6.9409127 ]
 [ 7.93992683]
 [ 4.72811714]
 [ 5.01984992]
 [ 4.98508672]
 [ 5.59453151]
 [ 6.27307854]
 [ 7.54090987]
 [ 8.53597251]
 [ 9.28844314]
 [10.50351783]
 [10.29906612]
 [10.27883838]
 [ 9.28123484]
 [ 6.38684332]
 [ 7.69254679]
 [ 5.10282931]
 [ 4.90737306]
 [ 5.20913389]
 [ 4.84607492]
 [ 7.3061802 ]
 [ 8.56893979]
 [ 9.17831749]
 [ 6.50062038]
 [ 8.08196807]
 [ 8.72207737]
 [ 9.86348494]
 [ 5.63674449]
 [ 7.18138224]
 [ 6.26555242]
 [ 6.01370854]
 [ 5.72964765]
 [ 9.92187

In [6]:
# Taxa de aprendizado
lr = 0.1

In [7]:
# Inicialização dos parâmetros
n_iterations = 1000
m = 100
theta = np.random.randn(2,1)

In [8]:
theta

array([[-1.39652536],
       [-0.4326486 ]])

In [9]:
# Adiciona coluna de 1s a X
X_b = np.c_[np.ones((m, 1)), X]

In [10]:
X_b

array([[1.        , 1.56161685],
       [1.        , 1.14319407],
       [1.        , 1.71228807],
       [1.        , 0.33859444],
       [1.        , 0.43720796],
       [1.        , 1.93338735],
       [1.        , 0.86421959],
       [1.        , 1.79714241],
       [1.        , 0.63653245],
       [1.        , 0.2927876 ],
       [1.        , 0.67142068],
       [1.        , 1.61191423],
       [1.        , 1.46757444],
       [1.        , 0.46405343],
       [1.        , 0.55699032],
       [1.        , 1.59740871],
       [1.        , 0.53193138],
       [1.        , 1.03197645],
       [1.        , 0.90537829],
       [1.        , 1.04465947],
       [1.        , 0.52411079],
       [1.        , 1.56455853],
       [1.        , 0.02274901],
       [1.        , 1.31363029],
       [1.        , 1.8180172 ],
       [1.        , 0.33801073],
       [1.        , 0.9456321 ],
       [1.        , 1.2385409 ],
       [1.        , 1.52811015],
       [1.        , 1.94679357],
       [1.

In [11]:
# Loop de treino
for iteration in range(n_iterations):
    
    
    # Calcula o gradiente (derivada parcial)
    gradients = 2/m * X_b.T.dot(X_b.dot(theta) - y)
    
    # Usa os gradientes para atualizar os coeficientes
    theta = theta - lr * gradients

In [12]:
print(gradients)

[[-1.21502808e-14]
 [ 6.52844684e-15]]


In [13]:
print(theta)

[[4.47640331]
 [3.05100078]]


In [14]:
theta[0]

array([4.47640331])

In [15]:
theta[1]

array([3.05100078])

y = coef1 + (coef2 * X)

Valor qualquer de X: 18

In [16]:
y = theta[0] + (theta[1] * 18)

In [17]:
print(y)

[59.39441727]


# Fim